# Updated 2025-05-20 23:45
[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = { Method = ["GET"], Path = ["/"] }