[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

# Redirects
[[redirects]]
  from = "/admin/*"
  to = "/static/admin/index.html" # Path relative to the 'publish' directory ("static")
  status = 200
  force = true

[[redirects]]
  from = "/reviewadmin/*"
  to = "/static/admin/index.html" # Path relative to the 'publish' directory ("static")
  status = 200
  force = true

# Catch-all for main index.html (adjust if your main index.html is also in 'static')
[[redirects]]
  from = "/*"
  to = "/static/index.html" # Path relative to the 'publish' directory ("static")
  status = 200
  force = false
  conditions = { Method = ["GET"], Path = ["/"] }