[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' blob: 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://media-library.cloudinary.com; connect-src 'self' https://api.netlify.com"

[[redirects]]
  from = "/invite"
  to = "/admin/"
  status = 301
  force = true