[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"
  environment = { NODE_VERSION = "16" }

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' blob: 'unsafe-inline'; connect-src 'self' https://login.artistictoolshub.com"

[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 302
  conditions = { Query = {} }

[[redirects]]
  from = "/invite"
  to = "/admin/cms"
  status = 301
  force = true