[build]
  command = "npm install"  # Simplified, assuming no custom build script is needed
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/static/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/reviewadmin/*"
  to = "/static/admin/index.html"  # Updated to point to the same admin page
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = { Method = ["GET"], Path = ["/"] }