[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"
  environment = { NODE_VERSION = "16" }

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' blob: 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://media-library.cloudinary.com; connect-src 'self' https://login.artistictoolshub.com https://api.netlify.com"

[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 302
  conditions = { Query = {} }