[build]
  command = "npm install"
  publish = "."
[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 302
  force = false
  conditions = { Query = {} }
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' blob: 'unsafe-inline'; connect-src 'self' https://login.artistictoolshub.com"
[functions]
  directory = "netlify/functions"