backend:
  name: git-gateway
  branch: main
  # Use auth_backend for external OAuth providers like Auth0
  auth_backend:
    name: external_oauth
    oauth_client_id: 'mbJ5rUjoVg7ztjnzO7MsHKlv66KYlkF1'
    # These URLs are from your Auth0 tenant
    oauth_url: 'https://dev-d07c5upcmrg0jedl.us.auth0.com/authorize'
    oauth_token_url: 'https://dev-d07c5upcmrg0jedl.us.auth0.com/oauth/token'
    oauth_authorize_url: 'https://dev-d07c5upcmrg0jedl.us.auth0.com/authorize'
    oauth_userinfo_url: 'https://dev-d07c5upcmrg0jedl.us.auth0.com/userinfo'
    oauth_pkce_enabled: true # Auth0 typically uses PKCE, enable this for better security
    # No client_secret here, as it's a public client-side application.
    # The client secret should never be exposed in frontend code or public config.
    # If you need to store secrets, use Netlify Environment Variables for backend functions,
    # but not in client-side config.
media_folder: "static/uploads"
public_folder: "/uploads" # This path is relative to the site root, which will be "static" now.
collections:
  - name: "creations"
    label: "Creations"
    folder: "content/creations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Text", name: "text", widget: "text", required: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }