backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: "drxmkv1si"
    api_key: "874188631367555"
    upload_preset: "artistictoolshub"

publish_mode: editorial_workflow
media_folder: "content/creations/images"
public_folder: "/creations/images"

collections:
  - name: "creations"
    label: "Creations"
    folder: "content/creations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Text", name: "text", widget: "text", required: true }
      - { label: "Image URL", name: "image", widget: "string", required: false }
      - { label: "Creator", name: "creator", widget: "string", required: false }
      - { label: "Published", name: "published", widget: "boolean", default: false }