backend:
  name: git-gateway
  branch: main  # Test with main branch first
  repo: mrcprlx/artistictoolshub

# Remove editorial_workflow to simplify
# publish_mode: editorial_workflow
media_folder: "content/creations/images"
public_folder: "/creations/images"

collections:
  - name: "creations"
    label: "Creations"
    folder: "content/creations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Text", name: "text", widget: "text", required: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Creator", name: "creator", widget: "string", required: false }
      - { label: "Published", name: "published", widget: "boolean", default: false }