backend:
  name: git-gateway
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: "creations"
    label: "Creations"
    folder: "content/creations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Text", name: "text", widget: "text", required: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }